### ISSUE TITLE
Add support for Django 4.1.3

### ISSUE THREAD

**Issue by mdublin** [praekelt/django-google-analytics#76]
Current pip is throwing the following error when trying to install the latest version of this package (5.0.6) with the [current Django version 4.1.3:](https://docs.djangoproject.com/en/4.1/releases/4.1.3/)

```
ERROR: Cannot install -r requirements.txt (line 22) and Django==4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Django==4.1.3
    django-google-analytics-app 5.0.6 depends on Django<4.1 and >=2.2.5
```

**Comment by rudigiesler** [comment]
The library hasn't been tested yet, and therefore doesn't yet support, Django 4.1. Will need to run the tests and see if any changes are required for 4.1, and then make a release for 4.1 support.

**Comment by rudigiesler** [comment]
Release 6.0.0 adds support for Django 4.1

**Comment by mdublin** [comment]
Thanks @rudigiesler!
